DROP TABLE IF EXISTS categories

CREATE TABLE categories (
	item_id int primary key not null,
    category_id INT,
    category_name VARCHAR(100)
);

SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS
where table_name = 'categories'

insert into 
	categories (item_id, category_id, category_name)
values
	(1, 1001, 'Electronics'),
	(2, 1002, 'Kitchen'),
	(3, 1003, 'Cosmetics')
	;

select * from categories

BEGIN ;

CREATE TABLE categories_back_up as select * from categories;

CREATE SEQUENCE categories_item_id_seq OWNED BY categories.item_id;
SELECT setval('categories_item_id_seq', (SELECT max(item_id) FROM categories));

ALTER TABLE categories
ALTER COLUMN item_id 
SET DEFAULT nextval('categories_item_id_seq');

INSERT INTO 
	categories (category_id, category_name) 
VALUES
  (1001, 'Fans'),
  (1001, 'Bulbs'),
  (1002, 'Stoves');

alter table categories
add constraint uq_categories_cat_name
unique (category_id, category_name);

COMMIT;

select * 
from information_schema.COLUMNS
where table_name = 'categories';

select * from categories_back_up

select * from categories
order by category_id

-- SCD 3 --

DROP TABLE IF EXISTS dim_product, stg_product;

create table dim_product (

	item_id int primary key,
	product_id int not null,
	product_name text not null,
	current_category text Not null,
	previous_category text,
	category_changed_on date
);

create table  stg_product(
    
	product_id   int,
    product_name text,
    category     text
)

-- Initial load (old structure)
INSERT INTO dim_product (product_id, product_name, current_category) VALUES
  (1, 'Table Fan', 'Electronics'),
  (2, 'LED Bulb',  'Electronics'),
  (3, 'Heater',  'Electronics'),
  (4, 'Gas Stove', 'Kitchen'),
  (5, 'Lipstick',  'Cosmetics');

select * from dim_product

create or replace procedure load_dim_product_scd3()
language plpgsql as 

$$
	BEGIN
		-- 1) Changed rows: shift current -> previous, then overwrite current
		update dim_product d

		set previous_category = d.current_category,
			current_category = s.category,
			category_changed_on = current_date

		from stg_product s

		where d.product_id = s.product_id
			AND d.current_category IS DISTINCT FROM s.category;

		-- 2) Brand-new rows
		insert into dim_product (product_id, product_name, current_category)
		select s.product_id, s.product_name, s.category
		FROM stg_product s
		where not exists (
			SELECT 1 FROM dim_product d WHERE d.product_id = s.product_id
		);
	END;
$$

INSERT INTO stg_product VALUES
  (1, 'Table Fan', 'Fans'),
  (2, 'LED Bulb',  'Bulbs'),
  (3, 'Gas Stove', 'Stoves'),
  (4, 'Lipstick',  'Cosmetics'),   -- unchanged
  (5, 'Kettle',    'Kitchen');     -- new

CALL load_dim_product_scd3();

SELECT * FROM dim_product ORDER BY product_id;


-- SCD3 on dim_product for the category split -- 

/*
Assumptions :

product_id is the business key (the product's identity in the source system).
item_id is the surrogate PK of the dimension row, so it needs to auto-generate.
categories holds the new structure, and current_category / previous_category store category_name values from it.
The load matches on product_id, never on item_id, so surrogate keys never get reassigned.

*/
DROP TABLE IF EXISTS dim_product, stg_product, categories;

-- New category structure (exactly as product specified)

CREATE TABLE categories (
    item_id       int PRIMARY KEY,
    category_id   int,
    category_name varchar(100) NOT NULL UNIQUE   -- unique so names can be validated/joined
);

INSERT INTO categories VALUES
  (1,1001,'Electronics'),
  (2,1001,'Fans'),
  (3,1001,'Bulbs'),
  (4,1002,'Kitchen'),
  (5,1002,'Stoves'),
  (6,1003,'Cosmetics');

select * from categories;

-- SCD3 dimension (item_id auto-generated)
CREATE TABLE dim_product (
    item_id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          int  NOT NULL UNIQUE,    -- business key, needed for matching
    product_name        text NOT NULL,
    current_category    text NOT NULL,
    previous_category   text,
    category_changed_on date
);

-- Staging: one row per product with its target category
CREATE TABLE stg_product (
    product_id   int,
    product_name text,
    category     text
);

-- Existing data under the OLD structure
INSERT INTO dim_product (product_id, product_name, current_category) VALUES
  (101, 'Table Fan',   'Electronics'),
  (102, 'LED Bulb',    'Electronics'),
  (103, 'Laptop',      'Electronics'),
  (104, 'Gas Stove',   'Kitchen'),
  (105, 'Mixer',       'Kitchen'),
  (106, 'Lipstick',    'Cosmetics');

select * from categories;
select * from dim_product;

INSERT INTO stg_product VALUES
  (101, 'Table Fan',  'Fans'),         -- Electronics -> Fans
  (102, 'LED Bulb',   'Bulbs'),        -- Electronics -> Bulbs
  (103, 'Laptop',     'Electronics'),  -- unchanged
  (104, 'Gas Stove',  'Stoves'),       -- Kitchen -> Stoves
  (105, 'Mixer',      'Kitchen'),      -- unchanged
  (106, 'Lipstick',   'Cosmetics'),    -- unchanged
  (107, 'Ceiling Fan','Fans');         -- brand new product
  
SELECT *
    FROM stg_product s
    LEFT JOIN categories c ON c.category_name = s.category
    WHERE c.category_name IS NULL;

create or replace procedure load_dim_product_scd3_2()
language plpgsql as 
$$
	declare bad_count int;
	Begin
		-- Guard: every staged category must exist in categories
		select count(*) into bad_count
		from stg_product s
		left join categories c on c.category_name = s.category
		WHERE c.category_name IS NULL;

		IF bad_count > 0 THEN
        	RAISE EXCEPTION '% staged rows have a category not in categories', bad_count;
    	END IF;
		
		-- 1) Changed: shift current -> previous, then overwrite current
		UPDATE dim_product d
    		SET previous_category   = d.current_category,   -- RHS sees the OLD value
        	current_category    = s.category,
        	category_changed_on = current_date
    	FROM stg_product s
    	WHERE d.product_id = s.product_id
      		AND d.current_category IS DISTINCT FROM s.category;
			  
		-- 2) New products (item_id comes from the identity)
	    INSERT INTO dim_product (product_id, product_name, current_category)
    	SELECT s.product_id, s.product_name, s.category
    	FROM stg_product s
    	WHERE NOT EXISTS (SELECT 1 FROM dim_product d WHERE d.product_id = s.product_id);	
	end;
$$

CALL load_dim_product_scd3_2();

SELECT * FROM dim_product ORDER BY product_id;
